//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cfg.Cards
{ 
    public enum ECardSet
    {
        /// <summary>
        /// 未知
        /// </summary>
        UNKNOWN = -1,
        /// <summary>
        /// 任何职业
        /// </summary>
        ANY = 0,
        /// <summary>
        /// 基本
        /// </summary>
        BASIC = 1,
        /// <summary>
        /// 专家
        /// </summary>
        EXPERT = 2,
        /// <summary>
        /// 奖励
        /// </summary>
        REWARD = 3,
        /// <summary>
        /// 任务
        /// </summary>
        MISSION = 4,
    }

} 
