//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cfg.Cards
{ 
    public enum ECardQuality
    {
        /// <summary>
        /// 未知
        /// </summary>
        UNKNOWN = -1,
        /// <summary>
        /// 任何
        /// </summary>
        ANY = 0,
        /// <summary>
        /// 免费
        /// </summary>
        FREE = 1,
        /// <summary>
        /// 普通
        /// </summary>
        Common = 2,
        /// <summary>
        /// 罕见
        /// </summary>
        RARE = 3,
        /// <summary>
        /// 史诗
        /// </summary>
        EPIC = 4,
        /// <summary>
        /// 传说
        /// </summary>
        LENGENDARY = 5,
    }

} 
