//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cfg.Cards
{ 
    public enum ECardType
    {
        /// <summary>
        /// 未知
        /// </summary>
        UNKNOWN = -1,
        /// <summary>
        /// 默认
        /// </summary>
        ANY = 0,
        /// <summary>
        /// 法术卡
        /// </summary>
        ATKMAGIC = 5,
        /// <summary>
        /// 英雄技能卡
        /// </summary>
        HEROSKILL = 10,
        /// <summary>
        /// 武器
        /// </summary>
        WEAPON = 7,
        /// <summary>
        /// 英雄
        /// </summary>
        HERO = 3,
        /// <summary>
        /// 侍从
        /// </summary>
        VALET = 4,
    }

} 
