//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cfg.Cards
{ 
    public enum ECardRace
    {
        /// <summary>
        /// 未知
        /// </summary>
        UNKNOWN = -1,
        /// <summary>
        /// 默认
        /// </summary>
        ANY = 0,
        /// <summary>
        /// 野兽
        /// </summary>
        BEAST = 1,
        /// <summary>
        /// 妖？
        /// </summary>
        DEMON = 2,
        /// <summary>
        /// 龙
        /// </summary>
        DRAGON = 3,
        /// <summary>
        /// 鱼人
        /// </summary>
        MURLOC = 4,
        /// <summary>
        /// 海岛
        /// </summary>
        PIRATE = 5,
        /// <summary>
        /// 图腾
        /// </summary>
        TOTEM = 6,
    }

} 
