//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cfg.Cards
{ 
    public enum ECardClass
    {
        /// <summary>
        /// 未知
        /// </summary>
        UNKNOWN = -1,
        /// <summary>
        /// 任何职业
        /// </summary>
        ANY = 0,
        /// <summary>
        /// 战士
        /// </summary>
        WARRIOR = 1,
        /// <summary>
        /// 圣骑士
        /// </summary>
        PALADIN = 2,
        /// <summary>
        /// 猎人
        /// </summary>
        HUNTER = 3,
        /// <summary>
        /// 恶人？
        /// </summary>
        ROGUE = 4,
        /// <summary>
        /// 牧师
        /// </summary>
        PRIEST = 5,
        /// <summary>
        /// 萨满
        /// </summary>
        SHAMA = 6,
        /// <summary>
        /// 魔法师
        /// </summary>
        MAGE = 7,
        /// <summary>
        /// 术士
        /// </summary>
        WARLOCK = 8,
        /// <summary>
        /// 德鲁伊
        /// </summary>
        DRUID = 9,
    }

} 
