//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Cfg.Cards
{ 

public sealed partial class TbCardAttrs
{
    private readonly Dictionary<int, Cards.CardAttrs> _dataMap;
    private readonly List<Cards.CardAttrs> _dataList;
    
    public TbCardAttrs(JSONNode _json)
    {
        _dataMap = new Dictionary<int, Cards.CardAttrs>();
        _dataList = new List<Cards.CardAttrs>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = Cards.CardAttrs.DeserializeCardAttrs(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Cards.CardAttrs> DataMap => _dataMap;
    public List<Cards.CardAttrs> DataList => _dataList;

    public Cards.CardAttrs GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Cards.CardAttrs Get(int key) => _dataMap[key];
    public Cards.CardAttrs this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}