//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;
using SimpleJSON;



namespace Cfg.Cards
{ 

public sealed partial class TbCard
{
    private readonly Dictionary<int, Cards.Card> _dataMap;
    private readonly List<Cards.Card> _dataList;
    
    public TbCard(JSONNode _json)
    {
        _dataMap = new Dictionary<int, Cards.Card>();
        _dataList = new List<Cards.Card>();
        
        foreach(JSONNode _row in _json.Children)
        {
            var _v = Cards.Card.DeserializeCard(_row);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }

    public Dictionary<int, Cards.Card> DataMap => _dataMap;
    public List<Cards.Card> DataList => _dataList;

    public Cards.Card GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Cards.Card Get(int key) => _dataMap[key];
    public Cards.Card this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    
    partial void PostInit();
    partial void PostResolve();
}

}