//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.Cards
{ 
    public enum ECardType
    {
        /// <summary>
        /// 侍从
        /// </summary>
        VALET = 4,
        /// <summary>
        /// 攻击类型的魔法
        /// </summary>
        ATKMAGIC = 5,
        /// <summary>
        /// 治疗魔法
        /// </summary>
        CUREMAGIC = 10,
        /// <summary>
        /// 武器
        /// </summary>
        WEAPON = 7,
        /// <summary>
        /// 英雄
        /// </summary>
        HERO = 3,
    }

} 
